<?php
require_once '../includes/db.php';

$ingredients = [
    "Abalone",
    "Abiyuch",
    "Acerola",
    "Achilleas",
    "Acorn",
    "Adobo",
    "Adzuki bean",
    "Agar",
    "Agave",
    "Akutaq",
    "Alaska blackfish",
    "Alaska pollock",
    "Alaska wild rhubarb",
    "Albacore tuna",
    "Alfalfa",
    "Allium",
    "Allspice",
    "Almond",
    "Alpine sweetvetch",
    "Alpinia",
    "Amaranth",
    "American butterfish",
    "American pokeweed",
    "American shad",
    "Anatidae",
    "Anchovy",
    "Angelica",
    "Anguilliformes",
    "Anise",
    "Anise Brandy",
    "Anise Hyssop",
    "Anise Oil",
    "Apple",
    "Apple Brandy",
    "Apple Cider Vinegar",
    "Apple Juice",
    "Apple Sauce",
    "Apricot",
    "Arabica coffee",
    "Arar",
    "Arepa",
    "Armagnac Brandy",
    "Arrack",
    "Arrowhead",
    "Arrowroot",
    "Artemisia",
    "Artichoke",
    "Asafoetida",
    "Ascidians",
    "Ashgourd",
    "Asparagus",
    "Atlantic croaker",
    "Atlantic halibut",
    "Atlantic herring",
    "Atlantic mackerel",
    "Atlantic menhaden",
    "Atlantic pollock",
    "Atlantic salmon",
    "Atlantic wolffish",
    "Avocado",
    "Babaco",
    "Babassu palm",
    "Bagel",
    "Baked potato",
    "Baking Powder",
    "Bamboo shoots",
    "Banana",
    "Bantu Beer",
    "Barley",
    "Bartlett Pear",
    "Basil",
    "Basmati Rice",
    "Bayberry",
    "Beans",
    "Bearded seal",
    "Beaver",
    "Beech nut",
    "Beef",
    "Beef Processed",
    "Beefalo",
    "Beer",
    "Beetroot",
    "Beli",
    "Beluga whale",
    "Bergamot",
    "Berry wine",
    "Bilberry",
    "Bilberry Wine",
    "Biscuit",
    "Bison",
    "Bitter Cherry",
    "Bitter Orange",
    "Bittergourd",
    "Bivalvia",
    "Black bear",
    "Black crowberry",
    "Black Currant",
    "Black huckleberry",
    "Black mulberry",
    "Black raspberry",
    "Black salsify",
    "Black Tea",
    "Blackberry",
    "Blackberry Brandy",
    "Black-eyed pea",
    "Blue Cheese",
    "Blue whiting",
    "Blueberry",
    "Bluefish",
    "Bonito",
    "Borage",
    "Botrytized Wine",
    "Bottlegourd",
    "Bourbon Whisky",
    "Bowhead whale",
    "Boysenberry",
    "Brandy",
    "Brazil Nut",
    "Bread",
    "Breadfruit",
    "Breakfast cereal",
    "Broad whitefish",
    "Broccoli",
    "Brown bear",
    "Brown Rice",
    "Brussels Sprout",
    "Buchu",
    "Buckwheat",
    "Buffalo",
    "Buffalo currant",
    "Bulgur",
    "Burbot",
    "Burdock",
    "Burrito",
    "Butter",
    "Buttermilk",
    "Butternut",
    "Butternut squash",
    "Byrsonima crassifolia",
    "Cabbage",
    "Cajeput",
    "Cake",
    "Calamus",
    "Camembert Cheese",
    "Camphor",
    "Canada blueberry",
    "Canadian Whisky",
    "Candy bar",
    "Canola Oil",
    "Capers",
    "Capsicum",
    "Caraway",
    "Cardamom",
    "Cardoon",
    "Caribou",
    "Carob",
    "Carom Seed",
    "Carp bream",
    "Carrot",
    "Cascarilla",
    "Casein",
    "Cashew Apple",
    "Cashew nut",
    "Cassava",
    "Cassia",
    "Catfish",
    "Catjang pea",
    "Cauliflower",
    "Caviar",
    "Cayenne",
    "Cedar",
    "Celery",
    "Ceriman",
    "Cetacea",
    "Chamomile",
    "Champaca",
    "Champagne",
    "Channel catfish",
    "Chanterelle",
    "Chard",
    "Charr",
    "Chayote",
    "Cheddar Cheese",
    "Cheese",
    "Cherimoya",
    "Cherry",
    "Cherry Brandy",
    "Cherry Pepper",
    "Cherry tomato",
    "Chervil",
    "Chestnut",
    "Chewing gum",
    "Chia",
    "Chicken",
    "Chickpea",
    "Chicory",
    "Chimichanga",
    "Chinese bayberry",
    "Chinese chestnut",
    "Chinese Quince",
    "Chinook salmon",
    "Chive",
    "Chocolate",
    "Chocolate mousse",
    "Chocolate spread",
    "Chum salmon",
    "Cichlidae",
    "Cider",
    "Cinnamon",
    "Cisco",
    "Citric Acid",
    "Citronella Oil",
    "Citrus Fruits",
    "Citrus Peel Oil",
    "Clam",
    "Clary Sage",
    "Climbing bean",
    "Cloud ear fungus",
    "Cloudberry",
    "Clove",
    "Clupeinae",
    "Cluster Bean",
    "Cocktail",
    "Cocoa",
    "Cocoa butter",
    "Cocoa powder",
    "Coconut",
    "Coconut Milk",
    "Coconut Oil",
    "Codfish",
    "Coffee",
    "Coffee mocha",
    "Cognac Brandy",
    "Coho salmon",
    "Cold cut",
    "Colocasia",
    "Colorado pinyon",
    "Columbidae",
    "Common carp",
    "Common dab",
    "Common ling",
    "Common octopus",
    "Common persimmon",
    "Common salsify",
    "Common Tuna",
    "Common verbena",
    "Comte Cheese",
    "Conch",
    "Condensed milk",
    "Cooking oil",
    "Cooking Spray",
    "Coriander",
    "Coriander Seed",
    "Corn",
    "Corn chip",
    "Corn grits",
    "Corn Oil",
    "Corn salad",
    "Cornbread",
    "Cornmint",
    "Cottage Cheese",
    "Cottonseed",
    "Couscous",
    "Crab",
    "Cranberry",
    "Crayfish",
    "Cream",
    "Cream Cheese",
    "Creosote",
    "Crispbread",
    "Cucumber",
    "Cucurbita",
    "Cumin",
    "Cured Ham",
    "Currant",
    "Curry Leaf",
    "Cusk",
    "Cuttlefish",
    "Dandelion",
    "Dates",
    "Deer",
    "Deerberry",
    "Devilfish",
    "Dill",
    "Dock",
    "Dolphin fish",
    "Domiati Cheese",
    "Drag̩e",
    "Drumstick Leaf",
    "Dulce de leche",
    "Dumpling",
    "Durian",
    "Egg",
    "Egg roll",
    "Eggplant",
    "Elderberry",
    "Elk",
    "Elliott's blueberry",
    "Emmental Cheese",
    "Empanada",
    "Emu",
    "Enchilada",
    "Endive",
    "Enokitake",
    "Epazote",
    "Eucalyptus Oil",
    "European anchovy",
    "European chestnut",
    "European rabbit",
    "Evaporated milk",
    "Evening primrose",
    "Falafel",
    "Fatty Fish",
    "Feijoa",
    "Fennel",
    "Fenugreek",
    "Fermented Tea",
    "Feta Cheese",
    "Fig",
    "Filbert",
    "Finnish Whisky",
    "Fir",
    "Fireweed",
    "Fish",
    "Fish burger",
    "Fish Oil",
    "Flatfish",
    "Flaxseed",
    "Florida pompano",
    "Flour",
    "Focaccia",
    "Food Coloring",
    "Frankfurter Sausage",
    "French plantain",
    "French toast",
    "Freshwater drum",
    "Freshwater eel",
    "Fried Potato",
    "Fruit gum",
    "Fruit juice",
    "Fruit salad",
    "Frybread",
    "Fudge",
    "Gadiformes",
    "Garcinia Indica",
    "Garden cress",
    "Garfish",
    "Garland chrysanthemum",
    "Garlic",
    "Gefilte fish",
    "Gelatin",
    "Gelatin",
    "Gelatin dessert",
    "Geranium",
    "Ghee",
    "Giant butterbur",
    "Gin",
    "Ginger",
    "Ginkgo nuts",
    "Ginseng",
    "Goat Cheese",
    "Goat Milk",
    "Gooseberry",
    "Gram bean",
    "Grape",
    "Grapefruit",
    "Grapefruit Peel Oil",
    "Grass",
    "Grass pea",
    "Great horned owl",
    "Greater sturgeon",
    "Green Beans",
    "Green Tea",
    "Green turtle",
    "Green zucchini",
    "Greenland halibut",
    "Greenthread tea",
    "Greylag goose",
    "Groundcherry",
    "Grouper",
    "Gruyere Cheese",
    "Guava",
    "Guinea hen",
    "Haddock",
    "Ham",
    "Hamburger",
    "Hard wheat",
    "Hazelnut",
    "Heart of palm",
    "Hedge mustard",
    "Hibiscus tea",
    "Hippoglossus",
    "Hogplum",
    "Honey",
    "Hops",
    "Hops Beer",
    "Hops Oil",
    "Horchata",
    "Horned melon",
    "Horse",
    "Horseradish",
    "Hot chocolate",
    "Hot dog",
    "Hummus",
    "Hushpuppy",
    "Hyacinth",
    "Hyacinth bean",
    "Hyssop Oil",
    "Ice cream",
    "Ice cream cone",
    "Icing",
    "Irish moss",
    "Jackfruit",
    "Jalapeno",
    "Japanese chestnut",
    "Japanese persimmon",
    "Japanese pumpkin",
    "Japanese Whisky",
    "Jasmine",
    "Jellyfish",
    "Jerusalem artichoke",
    "Jew's ear",
    "Jicama",
    "Jostaberry",
    "Jujube",
    "Junket",
    "Jute",
    "Kai lan",
    "Kale",
    "Kefir",
    "Kelp",
    "Kenaf",
    "Ketchup",
    "Kewda",
    "Kidney Beans",
    "King mackerel",
    "Kiwifruit",
    "Kohlrabi",
    "Komatsuna",
    "Kombu",
    "Krill",
    "Kumquat",
    "Lake trout",
    "Lamb",
    "Lambsquarters",
    "Lard",
    "Lasagna",
    "Laurel",
    "Lavendar",
    "Lean Fish",
    "Leather chiton",
    "Leavening agent",
    "Leek",
    "Lemon",
    "Lemon Balm",
    "Lemon Grass",
    "Lemon Juice",
    "Lemon Peel Oil",
    "Lemon sole",
    "Lemon verbena",
    "Lentils",
    "Lettuce",
    "Lima Beans",
    "Limburger Cheese",
    "Lime",
    "Lime Peel Oil",
    "Linden",
    "Lingcod",
    "Lingonberry",
    "Liqourice",
    "Liquid Smoke",
    "Litchi",
    "Lobster",
    "Loganberry",
    "Longan",
    "Loquat",
    "Lotus",
    "Lovage",
    "Lumpsucker",
    "Lupine",
    "Macadamia Nut",
    "Macaroni",
    "Mace",
    "Madeira wine",
    "Maitake",
    "Malabar plum",
    "Malabar spinach",
    "Malay Apple",
    "Malt",
    "Malt Whisky",
    "Mammee apple",
    "Mandarin Orange",
    "Mandarin Orange Peel Oil",
    "Mango",
    "Margarine",
    "Marjoram",
    "Marshmallow",
    "Marzipan",
    "Mastic Gum",
    "Mate",
    "Meat",
    "Meat bouillon",
    "Meatball",
    "Meatloaf",
    "Medlar",
    "Melon",
    "Mentha Oil",
    "Meringue",
    "Mexican groundcherry",
    "Mexican oregano",
    "Milk",
    "Milk Fat",
    "Milk Human",
    "Milk Powder",
    "Milkfish",
    "Milkshake",
    "Millet",
    "Mint",
    "Miso",
    "Mixed nuts",
    "Molasses",
    "Mollusc",
    "Monkfish",
    "Monosodium Glutamate",
    "Moose",
    "Morchella",
    "Moth bean",
    "Mountain hare",
    "Mountain Papaya",
    "Mountain yam",
    "Mozzarella Cheese",
    "Mulberry",
    "Mule deer",
    "Multigrain bread",
    "Mung bean",
    "Munster Cheese",
    "Muscadine grape",
    "Mushroom",
    "Musk Melon",
    "Muskmallow",
    "Muskrat",
    "Mustard",
    "Mustard Oil",
    "Mutton",
    "Myrrh",
    "Myrtle",
    "Nachos",
    "Nance",
    "Nanking cherry",
    "Naranjilla",
    "Narrowleaf cattail",
    "Natal plum",
    "Natto",
    "Neroli Oil",
    "New Zealand spinach",
    "Nigella Seed",
    "Nopal",
    "North Pacific giant octopus",
    "Northern bluefin tuna",
    "Northern pike",
    "Norway haddock",
    "Norway pout",
    "Nougat",
    "Nutmeg",
    "Nuttall cockle",
    "Oat bread",
    "Oats",
    "Ocean pout",
    "Ohelo berry",
    "Oil palm",
    "Oil-seed Camellia",
    "Okra",
    "Olive",
    "Onion",
    "Opossum",
    "Orange",
    "Orange Oil",
    "Orange roughy",
    "Oregano",
    "Oregon yampah",
    "Oriental wheat",
    "Orris",
    "Ostrich",
    "Ostrich fern",
    "Oyster",
    "Oyster mushroom",
    "Pacific herring",
    "Pacific jack mackerel",
    "Pacific ocean perch",
    "Pacific rockfish",
    "Pacific sardine",
    "Painted comber",
    "Pak choy",
    "Pan dulce",
    "Pancake",
    "Paneer",
    "Papaya",
    "Papaya Brandy",
    "Parmesan Cheese",
    "Parsley",
    "Parsnip",
    "Passionfruit",
    "Pasta",
    "Pastry",
    "Pate",
    "Pawpaw",
    "Peach",
    "Peanut",
    "Peanut Butter",
    "Peanut Oil",
    "Pear",
    "Pear Brandy",
    "Peas",
    "Pecans",
    "Pectin",
    "Pepino",
    "Pepper",
    "Peppermint",
    "Perciformes",
    "Percoidei",
    "Persimmon",
    "Pheasant",
    "Phyllo dough",
    "Pie",
    "Pie crust",
    "Pigeon Pea",
    "Pikeperch",
    "Piki bread",
    "Pili nut",
    "Pine",
    "Pineapple",
    "Pineappple sage",
    "Pink salmon",
    "Pistachio",
    "Pita bread",
    "Pitanga",
    "Pizza",
    "Pleuronectidae",
    "Plum",
    "Plum Brandy",
    "Plum Wine",
    "Plumcot",
    "Polar bear",
    "Pollock",
    "Pomegranate",
    "Popcorn",
    "Poppy Seed",
    "Pork",
    "Port Wine",
    "Pot pie",
    "Potato",
    "Potato bread",
    "Potato chip",
    "Potato gratin",
    "Potato puffs",
    "Prairie turnip",
    "Prawn",
    "Prickly Pear",
    "Provolone Cheese",
    "Pudding",
    "Pummelo",
    "Pumpkin",
    "Pumpkinseed sunfish",
    "Pupusa",
    "Purple laver",
    "Purple mangosteen",
    "Purslane",
    ",Quail",
    ",Quesadilla",
    ",Quince",
    ",Quinoa",
    "Rabbit",
    "Raccoon",
    "Radish",
    "Rainbow smelt",
    "Rainbow trout",
    "Raisin",
    "Raisin bread",
    "Rambutan",
    "Rapini",
    "Raspberry",
    "Raspberry Brandy",
    "Ravioli",
    "Red algae",
    "Red Currant",
    "Red king crab",
    "Red raspberry",
    "Red rice",
    "Red Sage",
    "Red Wine",
    "Redskin onion",
    "Relish",
    "Remoulade",
    "Rhubarb",
    "Rice",
    "Rice bread",
    "Rice cake",
    "Ricotta Cheese",
    "Ringed seal",
    "Rock ptarmigan",
    "Rocket salad",
    "Roe",
    "Roibos Tea",
    "Romano Cheese",
    "Roquefort Cheese",
    "Rose",
    "Rose hip",
    "Rose Wine",
    "Roseapple",
    "Roselle",
    "Rosemary",
    "Rowal",
    "Rowanberry",
    "Rum",
    "Russian Cheese",
    "Rutabaga",
    "Rye",
    "Rye Bread",
    "Sablefish",
    "Safflower",
    "Saffron",
    "Sage",
    "Sago palm",
    "Sake",
    "Salad",
    "Salad dressing",
    "Salmon",
    "Salmonberry",
    "Salmonidae",
    "Salt",
    "Sandalwood",
    "Sapodilla",
    "Saskatoon berry",
    "Sassafras",
    "Satsuma Orange",
    "Sauerkraut",
    "Sausage",
    "Scallop",
    "Scarlet bean",
    "Scombridae",
    "Scotch",
    "Scotch Spearmint",
    "Scrapple",
    "Scup",
    "Sea Buckthorns",
    "Sea cucumber",
    "Sea trout",
    "Semolina",
    "Sesame",
    "Sesbania flower",
    "Shallot",
    "Shark",
    "Shea tree",
    "Sheefish",
    "Sheep Cheese",
    "Sheep Milk",
    "Sheepshead",
    "Shellfish",
    "Sherry",
    "Shiitake",
    "Shortening",
    "Shrimp",
    "Silver linden",
    "Skimmed Milk",
    "Skunk currant",
    "Small leaf linden",
    "Smelt",
    "Smoked Fish",
    "Snack bar",
    "Snail",
    "Snapper",
    "Sockeye salmon",
    "Soft drink",
    "Sorghum",
    "Sorrel",
    "Soup",
    "Sour Cherry",
    "Sourdock",
    "Sourdough",
    "Soursop",
    "Soy cream",
    "Soy milk",
    "Soy yogurt",
    "Soybean",
    "Soybean Oil",
    "Soybean Sauce",
    "Spanish mackerel",
    "Spanish Sage",
    "Sparkleberry",
    "Sparkling Wine",
    "Spearmint",
    "Spelt",
    "Spinach",
    "Spineless Monkey Orange",
    "Spiny dogfish",
    "Spiny lobster",
    "Spirit",
    "Spirulina",
    "Spot croaker",
    "Spotted seal",
    "Spread",
    "Squab",
    "Squashberry",
    "Squid",
    "Squirrel",
    "Star Anise",
    "Starfruit",
    "Steller sea lion",
    "Stew",
    "Storax",
    "Strawberry",
    "Strawberry Jam",
    "Strawberry Wine",
    "Striped bass",
    "Striped mullet",
    "Stuffing",
    "Sturgeon",
    "Succotash",
    "Sugar",
    "Sukiyaki",
    "Summer savory",
    "Sunflower",
    "Swamp cabbage",
    "Sweet Cherry",
    "Sweet custard",
    "Sweet Grass",
    "Sweet Potato",
    "Sweetcorn",
    "Swiss Cheese",
    "Swordfish",
    "Syrup",
    "Taco",
    "Tamale",
    "Tamarind",
    "Tangerine",
    "Tapioca pearl",
    "Taro",
    "Tarragon",
    "Tartary buckwheat",
    "Tea",
    "Tea leaf willow",
    "Teff",
    "Tequila",
    "Thistle",
    "Thyme",
    "Tilefish",
    "Tilsit Cheese",
    "Tinda",
    "Tobacco",
    "Toffee",
    "Tofu",
    "Tomato",
    "Tomato Juice",
    "Tomato Paste",
    "Tomato Puree",
    "Topping",
    "Tortilla",
    "Tortilla chip",
    "Tostada",
    "Towel gourd",
    "Trail mix",
    "Trassi",
    "Tree fern",
    "Triticale",
    "True frog",
    "True seal",
    "True sole",
    "Truffle",
    "Turbot",
    "Turkey",
    "Turkey Berry",
    "Turmeric",
    "Turnip",
    "Ucuhuba",
    "Valerian",
    "Vanilla",
    "Vegetable juice",
    "Vermouth",
    "Vinegar",
    "Vodka",
    "Waffle",
    "Wakame",
    "Walleye",
    "Walnut",
    "Walrus",
    "Wasabi",
    "Water",
    "Water Chestnut",
    "Watercress",
    "Wattle",
    "Weinbrand Brandy",
    "Welsh onion",
    "Wheat",
    "Wheaten Bread",
    "Whelk",
    "Whey",
    "Whisky",
    "White Bread",
    "White Currant",
    "White lupine",
    "White Pepper",
    "White sucker",
    "White Wine",
    "Whitefish",
    "Whiting",
    "Wholewheat Bread",
    "Wild boar",
    "Wild duck",
    "Wild rice",
    "Wine",
    "Winged bean",
    "Winter savory",
    "Winter squash",
    "Wonton wrapper",
    "Woodapple",
    "Wort",
    "Yam",
    "Yardlong bean",
    "Yarrow",
    "Yautia",
    "Yeast",
    "Yellow Passionfruit",
    "Yellow pond lily",
    "Yellowfin tuna",
    "Yellowtail amberjack",
    "Ylang-Ylang",
    "Ymer",
    "Yogurt",
    "Zucchini",
    "Zwieback"

];

try {
    $pdo->beginTransaction();

    $checkIngredients = $pdo->prepare("SELECT COUNT(*) FROM ingredients WHERE name = ?");
    $insertIngredients = $pdo->prepare("INSERT INTO ingredients (name) VALUES (?)");

    foreach ($ingredients as $name) {
        $checkIngredients->execute([$name]);
        $exists = $checkIngredients->fetchColumn();

        if (!$exists) {
            $insertIngredients->execute([$name]);
        }
    }

    $pdo->commit();
    echo "Ingredients seeded successfully.";
} catch (Exception $e) {
    $pdo->rollBack();
    echo "Error seeding ingredients: " . $e->getMessage();
}
